### ISSUE TITLE
build the model 

### ISSUE THREAD

**Issue by AbuCyber100** [wagner-group/active-learning#3]
the steps to build the model  and what are the input of the model if I want to scan a apk

**Comment by surrealyz** [comment]
You may want to refer to a run script like this https://github.com/wagner-group/active-learning/blob/master/experiments/020_revision/scripts_ours/gen_apigraph_cnt10_088_warm_lr0.003_sgd_step_0.95_e250_adam_wlr0.00015_we50.sh (removing line 3, 5, 7), and go from there.
